import { readdir, readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";

import { Dependency } from "../../model/Dependency";
import { normalizePath } from "../../util/normalizePath";

const BARREL_FILE_NAME = "index.ts";
const GENERATED_FILE_HEADER = "// generated by entrysmith - don't change";

export async function applyBarrelFileChanges(dependency: Dependency): Promise<string[]> {
	if (dependency.config.barrelFileExtensions.length === 0) {
		return [];
	}

	const packageDirectory = path.dirname(dependency.packageJson.path);
	const barrelDirectoryList = dependency.config.entrypoints
		.map(normalizeEntrypointPath)
		.filter(entrypointPath => path.posix.basename(entrypointPath) === BARREL_FILE_NAME)
		.map(entrypointPath => path.resolve(packageDirectory, "src", path.posix.dirname(removeSourceDirectoryPrefix(entrypointPath))));
	const changedFilePathList: string[] = [];

	for (const barrelDirectory of [...new Set(barrelDirectoryList)].sort()) {
		const barrelFilePath = path.resolve(barrelDirectory, BARREL_FILE_NAME);
		const content = await createBarrelContent(barrelDirectory, dependency.config.barrelFileExtensions);
		if (await writeIfChanged(barrelFilePath, content)) {
			changedFilePathList.push(barrelFilePath);
		}
	}

	return changedFilePathList;
}

async function createBarrelContent(directory: string, extensionList: string[]): Promise<string> {
	const fileList = await readdir(directory, { withFileTypes: true });
	const exportPathList = fileList
		.filter(file => file.isFile())
		.map(file => file.name)
		.filter(fileName => path.parse(fileName).name !== "index")
		.filter(fileName => extensionList.includes(path.extname(fileName).slice(1)))
		.map(fileName => `./${path.basename(fileName, path.extname(fileName))}`)
		.sort();

	return [GENERATED_FILE_HEADER, "", ...exportPathList.map(exportPath => `export * from '${exportPath}';`), ""].join("\n");
}

function normalizeEntrypointPath(entrypointPath: string): string {
	return normalizePath(entrypointPath.trim().replace(/^\.[\\/]/, ""));
}

function removeSourceDirectoryPrefix(entrypointPath: string): string {
	return entrypointPath.startsWith("src/") ? entrypointPath.slice("src/".length) : entrypointPath;
}

async function writeIfChanged(filePath: string, content: string): Promise<boolean> {
	let existingContent: string | undefined;
	try {
		existingContent = await readFile(filePath, "utf8");
	} catch (error) {
		if (!isNotFoundError(error)) {
			throw error;
		}
	}

	if (existingContent === content) {
		return false;
	}

	await writeFile(filePath, content, "utf8");
	return true;
}

function isNotFoundError(error: unknown): error is NodeJS.ErrnoException {
	return typeof error === "object" && error !== null && "code" in error && error.code === "ENOENT";
}
